import { MigrationInterface, QueryRunner, TableColumn, TableIndex } from 'typeorm';

export class EnhanceUserFlags1750138800000 implements MigrationInterface {
  name = 'EnhanceUserFlags1750138800000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    // Create FlagStatus enum
    await queryRunner.query(`
      CREATE TYPE "public"."flag_status_enum" AS ENUM('ACTIVE', 'RESOLVED', 'APPEALED', 'EXPIRED', 'DISMISSED')
    `);

    // Add new columns to user_flags table
    await queryRunner.addColumns('user_flags', [
      new TableColumn({
        name: 'status',
        type: 'enum',
        enum: ['ACTIVE', 'RESOLVED', 'APPEALED', 'EXPIRED', 'DISMISSED'],
        default: `'ACTIVE'`,
      }),
      new TableColumn({
        name: 'metadata',
        type: 'jsonb',
        isNullable: true,
      }),
      new TableColumn({
        name: 'isAutoGenerated',
        type: 'boolean',
        default: false,
      }),
      new TableColumn({
        name: 'adminNote',
        type: 'text',
        isNullable: true,
      }),
      new TableColumn({
        name: 'resolution',
        type: 'text',
        isNullable: true,
      }),
      new TableColumn({
        name: 'createdById',
        type: 'uuid',
        isNullable: true,
      }),
      new TableColumn({
        name: 'resolvedById',
        type: 'uuid',
        isNullable: true,
      }),
      new TableColumn({
        name: 'resolvedAt',
        type: 'timestamp',
        isNullable: true,
      }),
      new TableColumn({
        name: 'appealReason',
        type: 'text',
        isNullable: true,
      }),
      new TableColumn({
        name: 'appealEvidence',
        type: 'jsonb',
        isNullable: true,
      }),
      new TableColumn({
        name: 'appealedAt',
        type: 'timestamp',
        isNullable: true,
      }),
      new TableColumn({
        name: 'appealResolution',
        type: 'text',
        isNullable: true,
      }),
      new TableColumn({
        name: 'appealResolvedById',
        type: 'uuid',
        isNullable: true,
      }),
      new TableColumn({
        name: 'appealResolvedAt',
        type: 'timestamp',
        isNullable: true,
      }),
      new TableColumn({
        name: 'expiresAt',
        type: 'timestamp',
        isNullable: true,
      }),
      new TableColumn({
        name: 'updatedAt',
        type: 'timestamp',
        default: 'now()',
      }),
    ]);

    // Create indexes
    await queryRunner.createIndex(
      'user_flags',
      new TableIndex({
        name: 'IDX_user_flags_user_type',
        columnNames: ['userId', 'type'],
      }),
    );

    await queryRunner.createIndex(
      'user_flags',
      new TableIndex({
        name: 'IDX_user_flags_status_severity',
        columnNames: ['status', 'severity'],
      }),
    );

    // Add foreign key constraints
    await queryRunner.query(`
      ALTER TABLE "user_flags" 
      ADD CONSTRAINT "FK_user_flags_createdBy" 
      FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE SET NULL
    `);

    await queryRunner.query(`
      ALTER TABLE "user_flags" 
      ADD CONSTRAINT "FK_user_flags_resolvedBy" 
      FOREIGN KEY ("resolvedById") REFERENCES "users"("id") ON DELETE SET NULL
    `);

    await queryRunner.query(`
      ALTER TABLE "user_flags" 
      ADD CONSTRAINT "FK_user_flags_appealResolvedBy" 
      FOREIGN KEY ("appealResolvedById") REFERENCES "users"("id") ON DELETE SET NULL
    `);

    console.log('✅ Enhanced user_flags table with new columns and indexes');
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // Remove foreign keys
    await queryRunner.query(
      `ALTER TABLE "user_flags" DROP CONSTRAINT IF EXISTS "FK_user_flags_appealResolvedBy"`,
    );
    await queryRunner.query(
      `ALTER TABLE "user_flags" DROP CONSTRAINT IF EXISTS "FK_user_flags_resolvedBy"`,
    );
    await queryRunner.query(
      `ALTER TABLE "user_flags" DROP CONSTRAINT IF EXISTS "FK_user_flags_createdBy"`,
    );

    // Remove indexes
    await queryRunner.dropIndex('user_flags', 'IDX_user_flags_status_severity');
    await queryRunner.dropIndex('user_flags', 'IDX_user_flags_user_type');

    // Remove columns
    await queryRunner.dropColumn('user_flags', 'updatedAt');
    await queryRunner.dropColumn('user_flags', 'expiresAt');
    await queryRunner.dropColumn('user_flags', 'appealResolvedAt');
    await queryRunner.dropColumn('user_flags', 'appealResolvedById');
    await queryRunner.dropColumn('user_flags', 'appealResolution');
    await queryRunner.dropColumn('user_flags', 'appealedAt');
    await queryRunner.dropColumn('user_flags', 'appealEvidence');
    await queryRunner.dropColumn('user_flags', 'appealReason');
    await queryRunner.dropColumn('user_flags', 'resolvedAt');
    await queryRunner.dropColumn('user_flags', 'resolvedById');
    await queryRunner.dropColumn('user_flags', 'createdById');
    await queryRunner.dropColumn('user_flags', 'resolution');
    await queryRunner.dropColumn('user_flags', 'adminNote');
    await queryRunner.dropColumn('user_flags', 'isAutoGenerated');
    await queryRunner.dropColumn('user_flags', 'metadata');
    await queryRunner.dropColumn('user_flags', 'status');

    // Drop enum
    await queryRunner.query(`DROP TYPE IF EXISTS "public"."flag_status_enum"`);

    console.log('✅ Reverted user_flags table changes');
  }
}
