import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1766048596421 implements MigrationInterface {
    name = 'InitialSchema1766048596421'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "wizard_questions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(100) NOT NULL, "label" text NOT NULL, "helpText" text, "inputType" character varying(50), "isActive" boolean NOT NULL DEFAULT true, "sortOrder" integer, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_fec5bf63c0e39ebf237b3bbc486" UNIQUE ("code"), CONSTRAINT "PK_01980ba9ae3a226aa28c08b2007" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."verification_documents_status_enum" AS ENUM('PENDING', 'VERIFIED', 'REJECTED')`);
        await queryRunner.query(`CREATE TABLE "verification_documents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "docType" character varying(100), "documentUrl" character varying NOT NULL, "status" "public"."verification_documents_status_enum" NOT NULL DEFAULT 'PENDING', "submittedAt" TIMESTAMP NOT NULL DEFAULT now(), "verifiedAt" TIMESTAMP, "verifiedBy" uuid, "rejectReason" text, CONSTRAINT "PK_b4dc59d87f87ce5a1bb1d3fe0bf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "wallets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "balance" numeric(15,2) NOT NULL DEFAULT '0', "currency" character varying(10) NOT NULL DEFAULT 'VND', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8402e5df5a30a229380e83e4f7e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2ecdb33f23e9a6fc392025c0b9" ON "wallets" ("userId") `);
        await queryRunner.query(`CREATE TABLE "wizard_options" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "questionId" uuid NOT NULL, "value" character varying(100) NOT NULL, "label" text NOT NULL, "sortOrder" integer, CONSTRAINT "PK_888ae1a4fab441bd429fcdc4452" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."user_tokens_type_enum" AS ENUM('EMAIL_VERIFICATION', 'PASSWORD_RESET')`);
        await queryRunner.query(`CREATE TYPE "public"."user_tokens_status_enum" AS ENUM('PENDING', 'USED', 'REVOKED')`);
        await queryRunner.query(`CREATE TABLE "user_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "type" "public"."user_tokens_type_enum" NOT NULL, "tokenHash" character varying NOT NULL, "status" "public"."user_tokens_status_enum" NOT NULL DEFAULT 'PENDING', "maxUses" integer NOT NULL DEFAULT '1', "useCount" integer NOT NULL DEFAULT '0', "expiresAt" TIMESTAMP NOT NULL, "usedAt" TIMESTAMP, "createdIp" character varying, "lastUsedIp" character varying, "lastUsedUserAgent" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_63764db9d9aaa4af33e07b2f4bf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_flags" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "type" character varying(100) NOT NULL, "severity" integer NOT NULL DEFAULT '1', "description" text NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6de618449277fb758cd2f13c1e3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('ADMIN', 'STAFF', 'BROKER', 'CLIENT', 'FREELANCER')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying(255) NOT NULL, "passwordHash" character varying(255), "fullName" character varying(255) NOT NULL, "role" "public"."users_role_enum" NOT NULL DEFAULT 'CLIENT', "phoneNumber" character varying(20), "isVerified" boolean NOT NULL DEFAULT false, "currentTrustScore" numeric(3,2) NOT NULL DEFAULT '5', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."transactions_type_enum" AS ENUM('DEPOSIT', 'HOLD', 'RELEASE', 'REFUND', 'WITHDRAWAL')`);
        await queryRunner.query(`CREATE TYPE "public"."transactions_status_enum" AS ENUM('PENDING', 'SUCCESS', 'FAILED', 'CANCELED')`);
        await queryRunner.query(`CREATE TABLE "transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "walletId" uuid NOT NULL, "amount" numeric(15,2) NOT NULL, "type" "public"."transactions_type_enum" NOT NULL, "status" "public"."transactions_status_enum" NOT NULL DEFAULT 'PENDING', "referenceType" character varying, "referenceId" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a219afd8dd77ed80f5a862f1db9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "trust_score_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "ratingScore" numeric(3,2), "behaviorScore" numeric(3,2), "disputeScore" numeric(3,2), "verificationScore" numeric(3,2), "totalScore" numeric(3,2), "calculatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_fc2095d09415689b51678b46615" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."tasks_status_enum" AS ENUM('TODO', 'IN_PROGRESS', 'IN_REVIEW', 'REVISIONS_REQUIRED', 'BLOCKED', 'DONE')`);
        await queryRunner.query(`CREATE TABLE "tasks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "milestoneId" uuid NOT NULL, "projectId" uuid NOT NULL, "title" character varying(255) NOT NULL, "description" text, "status" "public"."tasks_status_enum" NOT NULL DEFAULT 'TODO', "assignedTo" uuid, "dueDate" TIMESTAMP, "sortOrder" integer, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8d12ff38fcc62aaba2cab748772" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "saved_freelancers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "clientId" uuid NOT NULL, "freelancerId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c0ad842aac86d1014650bed12c1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f1d523469df6ac4e853b4bf531" ON "saved_freelancers" ("clientId", "freelancerId") `);
        await queryRunner.query(`CREATE TABLE "social_accounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "provider" character varying(50) NOT NULL, "providerId" character varying(255) NOT NULL, "email" character varying(255), "avatarUrl" text, "payload" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e9e58d2d8e9fafa20af914d9750" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "project_categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "slug" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_46046d6693cbabd6b882cd0e5d3" UNIQUE ("slug"), CONSTRAINT "PK_03d7af35c2601369d030b3617bc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."projects_pricingmodel_enum" AS ENUM('FIXED_PRICE', 'TIME_MATERIALS')`);
        await queryRunner.query(`CREATE TYPE "public"."projects_status_enum" AS ENUM('PLANNING', 'IN_PROGRESS', 'TESTING', 'COMPLETED', 'DISPUTED', 'CANCELED')`);
        await queryRunner.query(`CREATE TABLE "projects" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "requestId" uuid, "clientId" uuid NOT NULL, "brokerId" uuid NOT NULL, "freelancerId" uuid, "title" character varying(255) NOT NULL, "description" text NOT NULL, "totalBudget" numeric(15,2) NOT NULL, "currency" character varying(10) NOT NULL DEFAULT 'VND', "pricingModel" "public"."projects_pricingmodel_enum", "startDate" TIMESTAMP, "endDate" TIMESTAMP, "status" "public"."projects_status_enum" NOT NULL DEFAULT 'PLANNING', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6271df0a7aed1d6c0691ce6ac50" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "reviews" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "projectId" uuid NOT NULL, "reviewerId" uuid NOT NULL, "targetUserId" uuid NOT NULL, "rating" integer NOT NULL, "comment" text, "weight" numeric(3,2) NOT NULL DEFAULT '1', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_231ae565c273ee700b283f15c1d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_85132512bfb49b6441a05ffa0d" ON "reviews" ("projectId", "reviewerId", "targetUserId") `);
        await queryRunner.query(`CREATE TYPE "public"."project_requests_status_enum" AS ENUM('PENDING', 'PROCESSING', 'APPROVED', 'REJECTED', 'CANCELED')`);
        await queryRunner.query(`CREATE TABLE "project_requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "clientId" uuid NOT NULL, "title" character varying(255) NOT NULL, "description" text NOT NULL, "budgetRange" character varying, "intendedTimeline" character varying, "techPreferences" character varying, "status" "public"."project_requests_status_enum" NOT NULL DEFAULT 'PENDING', "brokerId" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_823e3ef5750d70abfbb943ee4ff" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "project_request_proposals" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "requestId" uuid NOT NULL, "freelancerId" uuid NOT NULL, "brokerId" uuid, "proposedBudget" numeric(15,2), "estimatedDuration" character varying, "coverLetter" text, "status" character varying NOT NULL DEFAULT 'PENDING', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e3a1f06e8f77e967076bd9404a6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_cac20fd0c92979420b2ae94d9b" ON "project_request_proposals" ("requestId", "freelancerId") `);
        await queryRunner.query(`CREATE TABLE "project_request_answers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "requestId" uuid NOT NULL, "questionId" uuid NOT NULL, "optionId" uuid, "valueText" text, CONSTRAINT "PK_ae029739fd856296276f8cbab69" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "bio" text, "companyName" character varying(255), "skills" text array, "portfolioLinks" jsonb, "bankInfo" jsonb, CONSTRAINT "REL_315ecd98bd1a42dcf2ec4e2e98" UNIQUE ("userId"), CONSTRAINT "PK_8e520eb4da7dc01d0e190447c8e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "platform_settings" ("key" character varying NOT NULL, "value" jsonb NOT NULL, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedBy" uuid, CONSTRAINT "PK_5d9031e30fac3ec3ec8b9602e17" PRIMARY KEY ("key"))`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "title" character varying(255) NOT NULL, "body" text NOT NULL, "isRead" boolean NOT NULL DEFAULT false, "readAt" TIMESTAMP, "relatedType" character varying, "relatedId" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."payout_requests_status_enum" AS ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'REJECTED')`);
        await queryRunner.query(`CREATE TABLE "payout_requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "walletId" uuid NOT NULL, "amount" numeric(15,2) NOT NULL, "status" "public"."payout_requests_status_enum" NOT NULL DEFAULT 'PENDING', "requestedAt" TIMESTAMP NOT NULL DEFAULT now(), "processedAt" TIMESTAMP, "processedBy" uuid, "note" text, CONSTRAINT "PK_3a6acb302f56ad7dadda35c86b8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."milestones_status_enum" AS ENUM('PENDING', 'IN_PROGRESS', 'LOCKED', 'COMPLETED', 'PAID')`);
        await queryRunner.query(`CREATE TABLE "milestones" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "projectId" uuid NOT NULL, "title" character varying(255) NOT NULL, "description" text, "amount" numeric(15,2) NOT NULL, "startDate" TIMESTAMP, "dueDate" TIMESTAMP, "status" "public"."milestones_status_enum" NOT NULL DEFAULT 'PENDING', "proofOfWork" character varying, "feedback" text, "sortOrder" integer, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0bdbfe399c777a6a8520ff902d9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."disputes_status_enum" AS ENUM('OPEN', 'IN_REVIEW', 'RESOLVED', 'REJECTED')`);
        await queryRunner.query(`CREATE TABLE "disputes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "projectId" uuid NOT NULL, "raisedBy" uuid NOT NULL, "against" uuid NOT NULL, "reason" text NOT NULL, "resolution" text, "status" "public"."disputes_status_enum" NOT NULL DEFAULT 'OPEN', "resolvedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3c97580d01c1a4b0b345c42a107" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "milestone_payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "milestoneId" uuid NOT NULL, "holdTransactionId" uuid, "releaseTransactionId" uuid, CONSTRAINT "PK_421444a538d4babff59b8921a60" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."documents_type_enum" AS ENUM('SRS', 'SDS', 'MOCKUP', 'REPORT', 'OTHER')`);
        await queryRunner.query(`CREATE TABLE "documents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "projectId" uuid NOT NULL, "uploaderId" uuid NOT NULL, "name" character varying(255) NOT NULL, "fileUrl" character varying NOT NULL, "type" "public"."documents_type_enum" NOT NULL, "version" integer NOT NULL DEFAULT '1', "description" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ac51aa5181ee2036f5ca482857c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "digital_signatures" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "contractId" uuid NOT NULL, "userId" uuid NOT NULL, "signatureHash" character varying NOT NULL, "ipAddress" character varying, "signedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_11dff7aef9846ed49b2134b0869" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "auth_sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "refreshTokenHash" character varying NOT NULL, "userAgent" character varying, "ipAddress" character varying, "isRevoked" boolean NOT NULL DEFAULT false, "revokedAt" TIMESTAMP, "expiresAt" TIMESTAMP NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "lastUsedAt" TIMESTAMP, "replacedBySessionId" uuid, "validAccessFrom" TIMESTAMP, CONSTRAINT "PK_641507381f32580e8479efc36cd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "contracts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "projectId" uuid NOT NULL, "title" character varying, "contractUrl" character varying NOT NULL, "termsContent" text, "status" character varying NOT NULL DEFAULT 'DRAFT', "createdBy" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2c7b8f3a7b1acdd49497d83d0fb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "actor_id" uuid NOT NULL, "action" character varying(100) NOT NULL, "entity_type" character varying(100) NOT NULL, "entity_id" character varying NOT NULL, "ip_address" character varying(45), "user_agent" text, "before_data" jsonb, "after_data" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c67935e88b6f1b7a82c56838fb" ON "audit_logs" ("actor_id", "entity_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "project_category_map" ("project_id" uuid NOT NULL, "category_id" uuid NOT NULL, CONSTRAINT "PK_20f09ce6ad412dfdf5adc394426" PRIMARY KEY ("project_id", "category_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_63d1dc4e442a80233613bc0d15" ON "project_category_map" ("project_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_02daa0e833626078f4b5c608ef" ON "project_category_map" ("category_id") `);
        await queryRunner.query(`ALTER TABLE "verification_documents" ADD CONSTRAINT "FK_e3acb36093f2773ea7893b4c972" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "verification_documents" ADD CONSTRAINT "FK_fc6a9c92a9cc696671c2561b73e" FOREIGN KEY ("verifiedBy") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD CONSTRAINT "FK_2ecdb33f23e9a6fc392025c0b97" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wizard_options" ADD CONSTRAINT "FK_aea0cfcb26193490328e6f14102" FOREIGN KEY ("questionId") REFERENCES "wizard_questions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_tokens" ADD CONSTRAINT "FK_92ce9a299624e4c4ffd99b645b6" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_flags" ADD CONSTRAINT "FK_87be2c376b9c867c1e12916c2af" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_a88f466d39796d3081cf96e1b66" FOREIGN KEY ("walletId") REFERENCES "wallets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trust_score_history" ADD CONSTRAINT "FK_6d46e08df04dfeb9f4311df2378" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_6dc5020fc4c6814347816455e7a" FOREIGN KEY ("milestoneId") REFERENCES "milestones"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_e08fca67ca8966e6b9914bf2956" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_3b34ce2db713f0be359768db816" FOREIGN KEY ("assignedTo") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "saved_freelancers" ADD CONSTRAINT "FK_66a3a09dc240f9edd007d8294b1" FOREIGN KEY ("clientId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "saved_freelancers" ADD CONSTRAINT "FK_32d1522472855a34af369949ad9" FOREIGN KEY ("freelancerId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "social_accounts" ADD CONSTRAINT "FK_7de933c3670ec71c68aca0afd56" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_026902dba3d3ceefa3817500674" FOREIGN KEY ("requestId") REFERENCES "project_requests"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_091f9433895a53408cb8ae3864f" FOREIGN KEY ("clientId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_8c56501d961c9f7b440abdce5d5" FOREIGN KEY ("brokerId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_22f434063fa3502539bab88858d" FOREIGN KEY ("freelancerId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_ee90086bb783380da5453d240b9" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_f9238c3e3739dc40322f577fc46" FOREIGN KEY ("reviewerId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_299e0ce9838de08dea4eac93e28" FOREIGN KEY ("targetUserId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_requests" ADD CONSTRAINT "FK_e207c2a029bb73b35ad1453426a" FOREIGN KEY ("clientId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_requests" ADD CONSTRAINT "FK_ba91413ed0daddd79814a09ef4d" FOREIGN KEY ("brokerId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_request_proposals" ADD CONSTRAINT "FK_a3e8fc57db73e22a5128c22e6c7" FOREIGN KEY ("requestId") REFERENCES "project_requests"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_request_proposals" ADD CONSTRAINT "FK_3a404d4e7ec6b5db69aa875cbf8" FOREIGN KEY ("freelancerId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_request_proposals" ADD CONSTRAINT "FK_36541dd025948b388251c3c01f4" FOREIGN KEY ("brokerId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_request_answers" ADD CONSTRAINT "FK_f80351df95d44f963e86f1c8d92" FOREIGN KEY ("requestId") REFERENCES "project_requests"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_request_answers" ADD CONSTRAINT "FK_bd1b708124a60b84cddb67a9fef" FOREIGN KEY ("questionId") REFERENCES "wizard_questions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_request_answers" ADD CONSTRAINT "FK_9e7d84f4f6c8c98fa0b733c5d5e" FOREIGN KEY ("optionId") REFERENCES "wizard_options"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "profiles" ADD CONSTRAINT "FK_315ecd98bd1a42dcf2ec4e2e985" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "platform_settings" ADD CONSTRAINT "FK_bf32a1bcd51436a0b202a00a834" FOREIGN KEY ("updatedBy") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_692a909ee0fa9383e7859f9b406" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payout_requests" ADD CONSTRAINT "FK_7ecca99cfa68cbb2bfade96cd05" FOREIGN KEY ("walletId") REFERENCES "wallets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payout_requests" ADD CONSTRAINT "FK_2efebf9c50eb838dd24d5816cc5" FOREIGN KEY ("processedBy") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "milestones" ADD CONSTRAINT "FK_662a1f9d865fe49768fa369fd0f" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "disputes" ADD CONSTRAINT "FK_9a4ad337edc45133e24c8bcaf4d" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "disputes" ADD CONSTRAINT "FK_5a6f52453994f5b71258623f811" FOREIGN KEY ("raisedBy") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "disputes" ADD CONSTRAINT "FK_59a083d59f0249a8af3346c07fa" FOREIGN KEY ("against") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "milestone_payments" ADD CONSTRAINT "FK_820aa06a348b448f9b6a8c52ad5" FOREIGN KEY ("milestoneId") REFERENCES "milestones"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "milestone_payments" ADD CONSTRAINT "FK_78f7c3195dff24da67bb49b29d5" FOREIGN KEY ("holdTransactionId") REFERENCES "transactions"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "milestone_payments" ADD CONSTRAINT "FK_372e96a14c5f890c42b0d6e58e0" FOREIGN KEY ("releaseTransactionId") REFERENCES "transactions"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_fe6ebd6e679c0feee3a7ecc0354" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_befd700a02312da4cc725ccaace" FOREIGN KEY ("uploaderId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "digital_signatures" ADD CONSTRAINT "FK_272d16a5c66344d957a1efecb25" FOREIGN KEY ("contractId") REFERENCES "contracts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "digital_signatures" ADD CONSTRAINT "FK_fda9661a44dca0e61b72fb4680a" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth_sessions" ADD CONSTRAINT "FK_925b24d7fc2f9324ce972aee025" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth_sessions" ADD CONSTRAINT "FK_6e11140db54eefb6f4991a40df0" FOREIGN KEY ("replacedBySessionId") REFERENCES "auth_sessions"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contracts" ADD CONSTRAINT "FK_2421e3588c8e452a325ca49b70f" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contracts" ADD CONSTRAINT "FK_754103da22018eef9a0ee6f21e5" FOREIGN KEY ("createdBy") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_177183f29f438c488b5e8510cdb" FOREIGN KEY ("actor_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_category_map" ADD CONSTRAINT "FK_63d1dc4e442a80233613bc0d154" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "project_category_map" ADD CONSTRAINT "FK_02daa0e833626078f4b5c608ef7" FOREIGN KEY ("category_id") REFERENCES "project_categories"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "project_category_map" DROP CONSTRAINT "FK_02daa0e833626078f4b5c608ef7"`);
        await queryRunner.query(`ALTER TABLE "project_category_map" DROP CONSTRAINT "FK_63d1dc4e442a80233613bc0d154"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_177183f29f438c488b5e8510cdb"`);
        await queryRunner.query(`ALTER TABLE "contracts" DROP CONSTRAINT "FK_754103da22018eef9a0ee6f21e5"`);
        await queryRunner.query(`ALTER TABLE "contracts" DROP CONSTRAINT "FK_2421e3588c8e452a325ca49b70f"`);
        await queryRunner.query(`ALTER TABLE "auth_sessions" DROP CONSTRAINT "FK_6e11140db54eefb6f4991a40df0"`);
        await queryRunner.query(`ALTER TABLE "auth_sessions" DROP CONSTRAINT "FK_925b24d7fc2f9324ce972aee025"`);
        await queryRunner.query(`ALTER TABLE "digital_signatures" DROP CONSTRAINT "FK_fda9661a44dca0e61b72fb4680a"`);
        await queryRunner.query(`ALTER TABLE "digital_signatures" DROP CONSTRAINT "FK_272d16a5c66344d957a1efecb25"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_befd700a02312da4cc725ccaace"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_fe6ebd6e679c0feee3a7ecc0354"`);
        await queryRunner.query(`ALTER TABLE "milestone_payments" DROP CONSTRAINT "FK_372e96a14c5f890c42b0d6e58e0"`);
        await queryRunner.query(`ALTER TABLE "milestone_payments" DROP CONSTRAINT "FK_78f7c3195dff24da67bb49b29d5"`);
        await queryRunner.query(`ALTER TABLE "milestone_payments" DROP CONSTRAINT "FK_820aa06a348b448f9b6a8c52ad5"`);
        await queryRunner.query(`ALTER TABLE "disputes" DROP CONSTRAINT "FK_59a083d59f0249a8af3346c07fa"`);
        await queryRunner.query(`ALTER TABLE "disputes" DROP CONSTRAINT "FK_5a6f52453994f5b71258623f811"`);
        await queryRunner.query(`ALTER TABLE "disputes" DROP CONSTRAINT "FK_9a4ad337edc45133e24c8bcaf4d"`);
        await queryRunner.query(`ALTER TABLE "milestones" DROP CONSTRAINT "FK_662a1f9d865fe49768fa369fd0f"`);
        await queryRunner.query(`ALTER TABLE "payout_requests" DROP CONSTRAINT "FK_2efebf9c50eb838dd24d5816cc5"`);
        await queryRunner.query(`ALTER TABLE "payout_requests" DROP CONSTRAINT "FK_7ecca99cfa68cbb2bfade96cd05"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_692a909ee0fa9383e7859f9b406"`);
        await queryRunner.query(`ALTER TABLE "platform_settings" DROP CONSTRAINT "FK_bf32a1bcd51436a0b202a00a834"`);
        await queryRunner.query(`ALTER TABLE "profiles" DROP CONSTRAINT "FK_315ecd98bd1a42dcf2ec4e2e985"`);
        await queryRunner.query(`ALTER TABLE "project_request_answers" DROP CONSTRAINT "FK_9e7d84f4f6c8c98fa0b733c5d5e"`);
        await queryRunner.query(`ALTER TABLE "project_request_answers" DROP CONSTRAINT "FK_bd1b708124a60b84cddb67a9fef"`);
        await queryRunner.query(`ALTER TABLE "project_request_answers" DROP CONSTRAINT "FK_f80351df95d44f963e86f1c8d92"`);
        await queryRunner.query(`ALTER TABLE "project_request_proposals" DROP CONSTRAINT "FK_36541dd025948b388251c3c01f4"`);
        await queryRunner.query(`ALTER TABLE "project_request_proposals" DROP CONSTRAINT "FK_3a404d4e7ec6b5db69aa875cbf8"`);
        await queryRunner.query(`ALTER TABLE "project_request_proposals" DROP CONSTRAINT "FK_a3e8fc57db73e22a5128c22e6c7"`);
        await queryRunner.query(`ALTER TABLE "project_requests" DROP CONSTRAINT "FK_ba91413ed0daddd79814a09ef4d"`);
        await queryRunner.query(`ALTER TABLE "project_requests" DROP CONSTRAINT "FK_e207c2a029bb73b35ad1453426a"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_299e0ce9838de08dea4eac93e28"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_f9238c3e3739dc40322f577fc46"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_ee90086bb783380da5453d240b9"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_22f434063fa3502539bab88858d"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_8c56501d961c9f7b440abdce5d5"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_091f9433895a53408cb8ae3864f"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_026902dba3d3ceefa3817500674"`);
        await queryRunner.query(`ALTER TABLE "social_accounts" DROP CONSTRAINT "FK_7de933c3670ec71c68aca0afd56"`);
        await queryRunner.query(`ALTER TABLE "saved_freelancers" DROP CONSTRAINT "FK_32d1522472855a34af369949ad9"`);
        await queryRunner.query(`ALTER TABLE "saved_freelancers" DROP CONSTRAINT "FK_66a3a09dc240f9edd007d8294b1"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_3b34ce2db713f0be359768db816"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_e08fca67ca8966e6b9914bf2956"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_6dc5020fc4c6814347816455e7a"`);
        await queryRunner.query(`ALTER TABLE "trust_score_history" DROP CONSTRAINT "FK_6d46e08df04dfeb9f4311df2378"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_a88f466d39796d3081cf96e1b66"`);
        await queryRunner.query(`ALTER TABLE "user_flags" DROP CONSTRAINT "FK_87be2c376b9c867c1e12916c2af"`);
        await queryRunner.query(`ALTER TABLE "user_tokens" DROP CONSTRAINT "FK_92ce9a299624e4c4ffd99b645b6"`);
        await queryRunner.query(`ALTER TABLE "wizard_options" DROP CONSTRAINT "FK_aea0cfcb26193490328e6f14102"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP CONSTRAINT "FK_2ecdb33f23e9a6fc392025c0b97"`);
        await queryRunner.query(`ALTER TABLE "verification_documents" DROP CONSTRAINT "FK_fc6a9c92a9cc696671c2561b73e"`);
        await queryRunner.query(`ALTER TABLE "verification_documents" DROP CONSTRAINT "FK_e3acb36093f2773ea7893b4c972"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_02daa0e833626078f4b5c608ef"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_63d1dc4e442a80233613bc0d15"`);
        await queryRunner.query(`DROP TABLE "project_category_map"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c67935e88b6f1b7a82c56838fb"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TABLE "contracts"`);
        await queryRunner.query(`DROP TABLE "auth_sessions"`);
        await queryRunner.query(`DROP TABLE "digital_signatures"`);
        await queryRunner.query(`DROP TABLE "documents"`);
        await queryRunner.query(`DROP TYPE "public"."documents_type_enum"`);
        await queryRunner.query(`DROP TABLE "milestone_payments"`);
        await queryRunner.query(`DROP TABLE "disputes"`);
        await queryRunner.query(`DROP TYPE "public"."disputes_status_enum"`);
        await queryRunner.query(`DROP TABLE "milestones"`);
        await queryRunner.query(`DROP TYPE "public"."milestones_status_enum"`);
        await queryRunner.query(`DROP TABLE "payout_requests"`);
        await queryRunner.query(`DROP TYPE "public"."payout_requests_status_enum"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TABLE "platform_settings"`);
        await queryRunner.query(`DROP TABLE "profiles"`);
        await queryRunner.query(`DROP TABLE "project_request_answers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cac20fd0c92979420b2ae94d9b"`);
        await queryRunner.query(`DROP TABLE "project_request_proposals"`);
        await queryRunner.query(`DROP TABLE "project_requests"`);
        await queryRunner.query(`DROP TYPE "public"."project_requests_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_85132512bfb49b6441a05ffa0d"`);
        await queryRunner.query(`DROP TABLE "reviews"`);
        await queryRunner.query(`DROP TABLE "projects"`);
        await queryRunner.query(`DROP TYPE "public"."projects_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."projects_pricingmodel_enum"`);
        await queryRunner.query(`DROP TABLE "project_categories"`);
        await queryRunner.query(`DROP TABLE "social_accounts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f1d523469df6ac4e853b4bf531"`);
        await queryRunner.query(`DROP TABLE "saved_freelancers"`);
        await queryRunner.query(`DROP TABLE "tasks"`);
        await queryRunner.query(`DROP TYPE "public"."tasks_status_enum"`);
        await queryRunner.query(`DROP TABLE "trust_score_history"`);
        await queryRunner.query(`DROP TABLE "transactions"`);
        await queryRunner.query(`DROP TYPE "public"."transactions_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."transactions_type_enum"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP TABLE "user_flags"`);
        await queryRunner.query(`DROP TABLE "user_tokens"`);
        await queryRunner.query(`DROP TYPE "public"."user_tokens_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."user_tokens_type_enum"`);
        await queryRunner.query(`DROP TABLE "wizard_options"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2ecdb33f23e9a6fc392025c0b9"`);
        await queryRunner.query(`DROP TABLE "wallets"`);
        await queryRunner.query(`DROP TABLE "verification_documents"`);
        await queryRunner.query(`DROP TYPE "public"."verification_documents_status_enum"`);
        await queryRunner.query(`DROP TABLE "wizard_questions"`);
    }

}
