import {
  Entity,
  Column,
  PrimaryGeneratedColumn,
  CreateDateColumn,
  UpdateDateColumn,
  ManyToOne,
  JoinColumn,
  Index,
} from 'typeorm';

/**
 * User Flag Status
 */
export enum FlagStatus {
  ACTIVE = 'ACTIVE',
  RESOLVED = 'RESOLVED',
  APPEALED = 'APPEALED',
  EXPIRED = 'EXPIRED',
  DISMISSED = 'DISMISSED',
}

@Entity('user_flags')
@Index(['userId', 'type'])
@Index(['status', 'severity'])
export class UserFlagEntity {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column()
  userId: string;

  @Column({ type: 'varchar', length: 100 })
  type: string;

  @Column({ type: 'int', default: 1 })
  severity: number; // 1-5: LOW, MEDIUM, HIGH, CRITICAL, SEVERE

  @Column({ type: 'text' })
  description: string;

  @Column({
    type: 'enum',
    enum: FlagStatus,
    default: FlagStatus.ACTIVE,
  })
  status: FlagStatus;

  // --- Metadata ---
  @Column({ type: 'jsonb', nullable: true })
  metadata: Record<string, any>;

  // --- Auto-generation tracking ---
  @Column({ default: false })
  isAutoGenerated: boolean;

  // --- Admin management ---
  @Column({ type: 'text', nullable: true })
  adminNote: string;

  @Column({ type: 'text', nullable: true })
  resolution: string;

  @Column({ nullable: true })
  createdById: string; // Admin who created (null if auto)

  @Column({ nullable: true })
  resolvedById: string;

  @Column({ type: 'timestamp', nullable: true })
  resolvedAt: Date;

  // --- Appeal system ---
  @Column({ type: 'text', nullable: true })
  appealReason: string;

  @Column({ type: 'jsonb', nullable: true })
  appealEvidence: string[];

  @Column({ type: 'timestamp', nullable: true })
  appealedAt: Date;

  @Column({ type: 'text', nullable: true })
  appealResolution: string;

  @Column({ nullable: true })
  appealResolvedById: string;

  @Column({ type: 'timestamp', nullable: true })
  appealResolvedAt: Date;

  // --- Expiration ---
  @Column({ type: 'timestamp', nullable: true })
  expiresAt: Date;

  // --- Timestamps ---
  @CreateDateColumn()
  createdAt: Date;

  @UpdateDateColumn()
  updatedAt: Date;

  // --- Relations ---
  @ManyToOne('UserEntity', { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'userId' })
  user: any;

  @ManyToOne('UserEntity', { onDelete: 'SET NULL' })
  @JoinColumn({ name: 'createdById' })
  createdBy: any;

  @ManyToOne('UserEntity', { onDelete: 'SET NULL' })
  @JoinColumn({ name: 'resolvedById' })
  resolvedBy: any;

  @ManyToOne('UserEntity', { onDelete: 'SET NULL' })
  @JoinColumn({ name: 'appealResolvedById' })
  appealResolvedBy: any;
}
