import {
  Entity,
  Column,
  PrimaryGeneratedColumn,
  CreateDateColumn,
  UpdateDateColumn,
  ManyToOne,
  JoinColumn,
  Index,
} from 'typeorm';

// =============================================================================
// ENUMS
// =============================================================================

export enum AvailabilityType {
  AVAILABLE = 'AVAILABLE', // Rảnh
  BUSY = 'BUSY', // Bận (có event khác)
  OUT_OF_OFFICE = 'OUT_OF_OFFICE', // Nghỉ phép
  PREFERRED = 'PREFERRED', // Khung giờ ưu tiên (thích nhất)
  DO_NOT_DISTURB = 'DO_NOT_DISTURB', // Không được book
}

// =============================================================================
// USER AVAILABILITY ENTITY (Lịch rảnh/bận)
// =============================================================================

/**
 * Lưu trữ lịch rảnh/bận của User.
 * Dùng cho: Staff (xử lý dispute), Freelancer/Client (họp dự án)
 * Hỗ trợ cả one-time và recurring.
 */
@Entity('user_availabilities')
@Index(['userId', 'startTime', 'endTime'])
@Index(['userId', 'type'])
export class UserAvailabilityEntity {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column()
  userId: string;

  // === TIME SLOT ===
  @Column({ type: 'timestamp', nullable: true, comment: 'Thời gian bắt đầu (cho one-time)' })
  startTime: Date;

  @Column({ type: 'timestamp', nullable: true, comment: 'Thời gian kết thúc (cho one-time)' })
  endTime: Date;

  @Column({ type: 'enum', enum: AvailabilityType })
  type: AvailabilityType;

  // === RECURRING (Cho giờ làm việc cố định hàng tuần) ===
  @Column({ default: false })
  isRecurring: boolean;

  @Column({ type: 'int', nullable: true, comment: 'Ngày trong tuần (0=CN, 1=T2, 2=T3...)' })
  dayOfWeek: number;

  @Column({ type: 'time', nullable: true, comment: 'Giờ bắt đầu recurring (08:00)' })
  recurringStartTime: string;

  @Column({ type: 'time', nullable: true, comment: 'Giờ kết thúc recurring (17:00)' })
  recurringEndTime: string;

  @Column({ type: 'date', nullable: true, comment: 'Ngày bắt đầu hiệu lực của recurring' })
  recurringStartDate: Date;

  @Column({ type: 'date', nullable: true, comment: 'Ngày kết thúc hiệu lực (null = vĩnh viễn)' })
  recurringEndDate: Date;

  // === AUTO-GENERATED (Khi có event, tự động tạo BUSY) ===
  @Column({ default: false, comment: 'TRUE = Tự động tạo từ CalendarEvent' })
  isAutoGenerated: boolean;

  @Column({ nullable: true, comment: 'CalendarEvent đã tạo availability này' })
  linkedEventId: string;

  // === NOTE ===
  @Column({ type: 'text', nullable: true, comment: 'Ghi chú (Họp nội bộ, Nghỉ phép...)' })
  note: string;

  @CreateDateColumn()
  createdAt: Date;

  @UpdateDateColumn()
  updatedAt: Date;

  // === RELATION ===
  @ManyToOne('UserEntity', { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'userId' })
  user: any;

  @ManyToOne('CalendarEventEntity', { nullable: true, onDelete: 'CASCADE' })
  @JoinColumn({ name: 'linkedEventId' })
  linkedEvent: any;
}
