from __future__ import annotations


FE16 = "Rating & Trust Score System"
FE17 = "Dispute Resolution System"
FE18 = "Notification System"


def case(
    id: str,
    feature: str,
    section: str,
    description: str,
    procedure: str,
    expected: str,
    dependencies: str,
) -> dict[str, str]:
    return {
        "id": id,
        "feature": feature,
        "section": section,
        "description": description,
        "procedure": procedure,
        "expectedResults": expected,
        "actualResults": "",
        "dependencies": dependencies,
        "result": "Untested",
        "testDate": "",
        "tester": "SonNT",
        "note": "",
        "evidenceRef": "",
    }


CASE_CATALOG = [
    case(
        "FE16-REV-01",
        FE16,
        "Review Creation & Eligibility",
        "Create a review successfully for an eligible paid/completed project and emit the downstream trust-score mutation event.",
        "1. Prepare a paid/completed project linked to reviewer and target user.\n2. Call ReviewService.create with valid rating/comment.\n3. Observe the review result, audit logging, and mutation event.",
        "1. Review creation succeeds.\n2. Transactional audit logging is called.\n3. The committed review mutation event is emitted.",
        "Eligible project exists, review tuple is unique, and review mutation event wiring is enabled.",
    ),
    case(
        "FE16-REV-02",
        FE16,
        "Review Creation & Eligibility",
        "Reject review creation when the project is not completed or paid yet.",
        "1. Prepare a project still in progress.\n2. Call ReviewService.create with an otherwise valid payload.\n3. Observe the exception path and side effects.",
        "1. The service rejects the request.\n2. No transaction starts.\n3. No mutation event is emitted.",
        "Project status remains outside COMPLETED/PAID and the payload is otherwise valid.",
    ),
    case(
        "FE16-REV-03",
        FE16,
        "Review Creation & Eligibility",
        "Rollback review creation when an in-transaction audit log write fails.",
        "1. Prepare an eligible review creation flow.\n2. Force AuditLogsService.logOrThrow to fail inside the transaction.\n3. Call ReviewService.create and observe rollback behavior.",
        "1. The flow throws the original transaction failure.\n2. The write path does not complete as a committed success.\n3. No trust-score mutation event is emitted.",
        "Eligible review payload and a forced audit log failure inside the transactional branch.",
    ),
    case(
        "FE16-REV-04",
        FE16,
        "Review Update & Edit History",
        "Update an existing review and emit the committed trust-score mutation event after persistence.",
        "1. Prepare an existing editable review.\n2. Call ReviewService.update with new rating/comment.\n3. Observe the updated review payload, audit log write, and event emission.",
        "1. The review reflects the new rating/comment.\n2. Update audit logging is recorded.\n3. A committed mutation event is emitted.",
        "Review exists, belongs to the current reviewer, and remains inside the editable window.",
    ),
    case(
        "FE16-REV-05",
        FE16,
        "Review Moderation",
        "Reject moderation mutations that use a stale assignmentVersion and rollback the moderation transaction.",
        "1. Prepare a moderated review with assignmentVersion newer than the caller value.\n2. Invoke an open/take/release/reassign moderation mutation with the stale version.\n3. Observe the transaction result.",
        "1. ConflictException is thrown.\n2. No moderation save occurs.\n3. The query runner rolls back and no moderation audit log is written.",
        "Review moderation case exists and the caller submits an outdated assignmentVersion token.",
    ),
    case(
        "FE16-TPR-01",
        FE16,
        "Trust Profile Retrieval",
        "Return a full trust profile payload for an active user through the guarded HTTP endpoint.",
        "1. Seed active users, profiles, one project, and one review in Postgres.\n2. Sign a real JWT and call GET /trust-profiles/:userId.\n3. Inspect the mapped user, reviews, and projectHistory payload.",
        "1. HTTP 200 is returned.\n2. The payload includes mapped trust-profile user fields, review details, and project history.\n3. JwtAuthGuard is exercised with a real token.",
        "Postgres test container is healthy, JWT secrets are configured, and seeded user/project/review data exists.",
    ),
    case(
        "FE16-TPR-02",
        FE16,
        "Trust Profile Retrieval",
        "Return HTTP 404 for a missing trust profile even when authentication succeeds.",
        "1. Seed only the authenticated caller.\n2. Sign a real JWT and call GET /trust-profiles/:userId for a non-existent user id.\n3. Observe the response status and error message.",
        "1. HTTP 404 is returned.\n2. The response message is User not found.\n3. Authentication still succeeds before the service rejects the missing user.",
        "JWT secrets are configured and the requested user id does not exist as an ACTIVE user.",
    ),
    case(
        "FE16-TS-01",
        FE16,
        "Trust Score Calculation & History",
        "Recalculate trust score through the guarded HTTP endpoint using only active reviews and persist a history row.",
        "1. Seed the target user, supporting users, and both active and soft-deleted reviews.\n2. Sign a real JWT and call POST /trust-score/calculate/:userId.\n3. Inspect the response, refreshed user score, and trust_score_history row.",
        "1. HTTP 201 is returned with oldScore/newScore.\n2. The recalculated score is persisted.\n3. One trust_score_history row is written and deleted reviews are excluded.",
        "Authenticated caller exists and at least one active review is seeded for the target user.",
    ),
    case(
        "FE16-TS-02",
        FE16,
        "Trust Score Calculation & History",
        "Return trust score history in descending order while honoring the requested limit parameter.",
        "1. Seed two trust score history rows for the same user.\n2. Sign a real JWT and call GET /trust-score/history/:userId?limit=1.\n3. Inspect the returned collection ordering and length.",
        "1. HTTP 200 is returned.\n2. Exactly one newest row is returned because limit=1.\n3. The history is ordered by calculatedAt descending.",
        "Authenticated caller exists and trust score history rows are already persisted for the target user.",
    ),
    case(
        "FE17-DIS-01",
        FE17,
        "Dispute Intake & Listing",
        "Create a grouped dispute request atomically for multiple defendants and return root/group information.",
        "1. Prepare a createGroup request with multiple defendants.\n2. Execute DisputesService.createGroup.\n3. Observe transaction commit and the returned root/group summary.",
        "1. The transaction commits once after all grouped disputes are created.\n2. The payload contains rootDisputeId, groupId, createdCount, and child dispute references.\n3. Post-create side effects run only after success.",
        "The milestone is valid, defendants are unique, and no conflicting active dispute already exists.",
    ),
    case(
        "FE17-DIS-02",
        FE17,
        "Dispute Intake & Listing",
        "Reject a grouped dispute request that contains duplicate defendant ids before any transactional creation begins.",
        "1. Prepare a createGroup request containing the same defendant id twice.\n2. Execute DisputesService.createGroup.\n3. Observe the exception path and side effects.",
        "1. BadRequestException is thrown.\n2. No transactional create helper is invoked.\n3. No grouped dispute records are committed.",
        "The duplicate ids are supplied in the same createGroup payload and all other fields are otherwise valid.",
    ),
    case(
        "FE17-DIS-03",
        FE17,
        "Dispute Intake & Listing",
        "Rollback the entire grouped dispute creation when one defendant insert fails mid-transaction.",
        "1. Prepare a grouped create request with more than one defendant.\n2. Force the second createDisputeWithinTransaction call to fail.\n3. Execute DisputesService.createGroup.",
        "1. The insertion failure is surfaced.\n2. The query runner rolls back once.\n3. No post-create side effects run.",
        "At least two defendants are requested and one transactional creation branch is forced to fail.",
    ),
    case(
        "FE17-EVD-01",
        FE17,
        "Evidence Management",
        "Accept a supported PNG evidence upload during validation.",
        "1. Call EvidenceService.validateFileUpload with a .png filename, image/png content type, and valid size.\n2. Observe the validation result.",
        "1. The validation result isValid=true.\n2. No unsupported-file rejection is returned.",
        "The filename, mime type, and file size match the allowed evidence upload rules.",
    ),
    case(
        "FE17-EVD-02",
        FE17,
        "Evidence Management",
        "Reject an unsupported executable attachment during evidence upload validation.",
        "1. Call EvidenceService.validateFileUpload with a .exe filename and application/x-msdownload content type.\n2. Observe the validation result.",
        "1. The validation result isValid=false.\n2. Unsupported file type protection triggers before persistence.",
        "The attempted file type is outside the supported allow-list.",
    ),
    case(
        "FE17-HEA-01",
        FE17,
        "Hearing Lifecycle",
        "Return only actionable hearings when filtering the hearing lifecycle for active records.",
        "1. Prepare a hearing repository response that mixes actionable and archived lifecycle candidates.\n2. Execute the active lifecycle query helper.\n3. Inspect the returned payload.",
        "1. Only actionable hearings are returned.\n2. Archived or non-actionable hearings are filtered out.\n3. The lifecycle summary matches the frontend contract.",
        "The hearing dataset contains both active and archived lifecycle records.",
    ),
    case(
        "FE17-HEA-02",
        FE17,
        "Hearing Lifecycle",
        "Auto-close only hearings that exceeded the configured grace window.",
        "1. Prepare overdue and non-overdue hearing records.\n2. Execute HearingService.autoCloseOverdueHearings.\n3. Inspect checked/closed counters.",
        "1. Only hearings beyond the grace window are auto-closed.\n2. Non-overdue hearings remain untouched.\n3. The counters distinguish checked, closed, and failed items.",
        "At least one in-progress hearing has passed its grace window and one has not.",
    ),
    case(
        "FE17-VER-01",
        FE17,
        "Verdict Readiness & Issuance",
        "Forbid a staff user who is not the assigned moderator from issuing a hearing verdict.",
        "1. Prepare an in-progress hearing with staff-1 as moderator.\n2. Attempt issueHearingVerdict as staff-2.\n3. Observe the authorization result.",
        "1. ForbiddenException is thrown.\n2. Verdict issuance is blocked before payout calculation or hearing close logic runs.",
        "The hearing exists, is in progress, and the acting staff user is not the assigned moderator.",
    ),
    case(
        "FE17-VER-02",
        FE17,
        "Verdict Readiness & Issuance",
        "Compute split payout amounts from splitRatioClient and close the hearing after verdict issuance.",
        "1. Prepare an active hearing, funded escrow, and a ready verdict DTO with result=SPLIT.\n2. Execute issueHearingVerdict as the assigned moderator.\n3. Inspect the issued verdict payload, payout amounts, and hearing close response.",
        "1. Split amounts are computed from splitRatioClient.\n2. VerdictService.issueVerdict receives the computed payout amounts.\n3. HearingService.endHearing is called and the response includes verdict, hearing, and transfer summary.",
        "The hearing is active, readiness checks pass, and the associated escrow record exists with enough balance.",
    ),
    case(
        "FE17-SET-01",
        FE17,
        "Settlement & Appeal",
        "Validate an exact settlement distribution and compute platform fee breakdown for a valid offer.",
        "1. Execute SettlementService.validateMoneyLogic with client/freelancer amounts that sum exactly to the funded escrow amount.\n2. Inspect the returned fee breakdown.",
        "1. The validation result is valid=true.\n2. The breakdown includes fees and net amounts.\n3. No precision drift occurs in the computed totals.",
        "amountToClient plus amountToFreelancer equals the funded escrow amount exactly and both values are non-negative.",
    ),
    case(
        "FE17-SET-02",
        FE17,
        "Settlement & Appeal",
        "Block settlement eligibility when a pending settlement offer already exists for the dispute.",
        "1. Prepare a dispute in a settlement-eligible status and mock an existing pending settlement.\n2. Execute SettlementService.checkSettlementEligibility.\n3. Inspect the eligibility result.",
        "1. The service returns eligible=false.\n2. The reason states that a pending settlement offer already exists.",
        "The dispute exists in a settlement-eligible status and a pending settlement row already exists.",
    ),
    case(
        "FE17-APL-01",
        FE17,
        "Settlement & Appeal",
        "Submit an appeal and merge additional evidence into the dispute record.",
        "1. Prepare a resolved dispute eligible for appeal.\n2. Execute DisputesService.submitAppeal with a long reason, disclaimer acceptance, and new evidence ids.\n3. Inspect the verdict-service delegation and persisted evidence array.",
        "1. VerdictService.appealVerdict is called.\n2. Additional evidence is merged into the dispute record.\n3. The updated appealed dispute is returned.",
        "The dispute is in a state that allows appeal submission and the caller is the legitimate dispute party.",
    ),
    case(
        "FE17-APL-02",
        FE17,
        "Settlement & Appeal",
        "Reject appeal resolution attempts from non-admin staff.",
        "1. Prepare a staff caller without ADMIN role.\n2. Execute DisputesService.resolveAppeal.\n3. Observe the authorization result.",
        "1. ForbiddenException is thrown.\n2. Appeal verdict issuance is not delegated to VerdictService.",
        "The acting user is STAFF instead of ADMIN and attempts to resolve an appeal.",
    ),
    case(
        "FE17-APL-03",
        FE17,
        "Settlement & Appeal",
        "Resolve an appeal as ADMIN and delegate the final appeal verdict to the verdict service.",
        "1. Prepare an appealed dispute and an admin caller.\n2. Execute DisputesService.resolveAppeal with the appeal verdict payload.\n3. Inspect the delegated verdict issuance and resulting dispute state.",
        "1. VerdictService.issueAppealVerdict is called with override metadata.\n2. Appeal activity logging is saved.\n3. The resulting dispute returns in a resolved state.",
        "The dispute is in APPEALED status and the acting user has ADMIN role.",
    ),
    case(
        "FE17-ADM-01",
        FE17,
        "Staff Assignment / Admin Controls",
        "Compute dashboard multi-party risk signals with enum-safe broker dispute filters.",
        "1. Prepare dashboard repository mocks for disputes, hearings, evidence, staff performance, and workload.\n2. Execute StaffAssignmentService.getDashboardOverview.\n3. Inspect throughput, scheduling, and riskSignals.",
        "1. Broker-related dispute types are included through enum-safe filters.\n2. The returned dashboard contains throughput, scheduling, and riskSignals aggregates.\n3. Multi-party and conflicting-evidence counts match the prepared values.",
        "Dashboard repositories include both broker-related and grouped dispute data.",
    ),
    case(
        "FE18-NOT-01",
        FE18,
        "Notification Listing & Pagination",
        "Block unauthenticated notification listing requests at JwtAuthGuard before controller logic runs.",
        "1. Call GET /notifications without Bearer token.\n2. Observe the HTTP response.",
        "1. HTTP 401 Unauthorized is returned.\n2. The request is rejected before any notification list payload is produced.",
        "The notifications controller is protected by JwtAuthGuard and no access token is supplied.",
    ),
    case(
        "FE18-NOT-02",
        FE18,
        "Notification Listing & Pagination",
        "Return paginated unread notifications for the authenticated user with the frontend response contract.",
        "1. Seed read and unread notifications for the caller and another user.\n2. Call GET /notifications with page, limit, and unreadOnly=true using a real JWT.\n3. Inspect the response shape and filtered records.",
        "1. HTTP 200 with success=true is returned.\n2. Only the signed-in user's unread records are returned.\n3. Pagination metadata total/page/limit is correct.",
        "Postgres test container is healthy, JWT auth succeeds, and notifications are seeded for multiple users.",
    ),
    case(
        "FE18-NOT-06",
        FE18,
        "Unread Filtering",
        "Apply unreadOnly filtering so read notifications and foreign-user notifications are excluded from the result set.",
        "1. Seed read and unread notifications across two users.\n2. Call GET /notifications with unreadOnly=true using a real JWT.\n3. Inspect the returned item set.",
        "1. Only unread notifications owned by the authenticated user remain in the response.\n2. Read rows and other-user rows are filtered out.",
        "The response dataset contains a mix of read/unread rows and more than one user so filtering behavior can be observed.",
    ),
    case(
        "FE18-NOT-03",
        FE18,
        "Mark Single Read",
        "Mark a notification as read through the HTTP endpoint and keep the operation idempotent on repeated requests.",
        "1. Seed one unread notification for the caller.\n2. Call PATCH /notifications/:id/read twice using the same JWT.\n3. Inspect the responses and persisted row.",
        "1. The first request sets isRead=true with readAt.\n2. The second request still returns success without duplicate side effects.\n3. The row remains persisted as read.",
        "Authenticated user owns the target notification and it starts unread.",
    ),
    case(
        "FE18-NOT-04",
        FE18,
        "Mark All Read",
        "Bulk mark all unread notifications as read for the authenticated user without touching other users' data.",
        "1. Seed unread notifications for the caller and another user.\n2. Call PATCH /notifications/read-all using a real JWT.\n3. Inspect the response and persisted rows.",
        "1. HTTP 200 with success=true is returned.\n2. All unread notifications of the caller become read.\n3. Other users' notifications remain unchanged.",
        "Authenticated caller has unread notifications and another user's unread notification exists for isolation checking.",
    ),
    case(
        "FE18-NOT-05",
        FE18,
        "Notification Creation & Realtime Dispatch",
        "Persist a notification through the real service and dispatch notification.created to the event bus.",
        "1. Seed the target user.\n2. Subscribe to notification.created in the integration harness.\n3. Call NotificationsService.create with real repository and event-emitter wiring.\n4. Inspect the persisted row and captured event payload.",
        "1. One notification row is persisted with trimmed title/body.\n2. notification.created is emitted exactly once with the saved notification id.\n3. The payload carries the expected userId and related metadata.",
        "EventEmitterModule and NotificationsService are wired with the real TypeORM repository in the integration harness.",
    ),
]
