import { buildCaseLogMessageFromTitle } from './test-log-helpers';
import type { WorkbookCaseDescriptor } from './case-catalog.types';
import {
  ADMIN_ID,
  EVENT_ID,
  OTHER_EVENT_ID,
  OTHER_USER_ID,
  PARTICIPANT_ID,
  REQUEST_ID,
  SAMPLE_END,
  SAMPLE_START,
  USER_ID,
} from './calendar-test-factory';

const makeCase = (
  title: string,
  type: WorkbookCaseDescriptor['type'],
  preconditions: string[],
  inputs: Record<string, unknown>,
  returns: string[],
  exceptions: string[],
): WorkbookCaseDescriptor => {
  const match = title.match(/(UTC\d+)/);
  const utcId = match?.[1] ?? 'UTC00';
  const testKey = title.match(/(EP-\d+\s+UTC\d+)/)?.[1] ?? title;

  return {
    utcId,
    testKey,
    title,
    type,
    preconditions,
    inputs,
    returns,
    exceptions,
    logs: [buildCaseLogMessageFromTitle(title)],
  };
};

const MANUAL_CASES: Record<string, WorkbookCaseDescriptor[]> = {
  'EP-003': [
    makeCase(
      'EP-003 UTC01 happy path returns overview for a valid range input',
      'N',
      [
        'Authenticated ADMIN user invokes AdminDashboardController.getOverview',
        'Analytics dependencies are available',
      ],
      { range: '7d' },
      ['returns overview payload for range = "7d"'],
      [],
    ),
    makeCase(
      'EP-003 UTC02 edge case defaults the range input to 30d when it is omitted',
      'B',
      [
        'Authenticated ADMIN user invokes AdminDashboardController.getOverview',
        'Caller omits the optional range input',
      ],
      { range: null },
      ['returns overview payload for default range = "30d"'],
      [],
    ),
    makeCase(
      'EP-003 UTC03 edge case normalizes an unsupported range input to 30d',
      'B',
      [
        'Authenticated ADMIN user invokes AdminDashboardController.getOverview',
        'Service normalizes unsupported range aliases to the default range',
      ],
      { range: '365d' },
      ['returns overview payload for normalized range = "30d"'],
      [],
    ),
    makeCase(
      'EP-003 UTC04 validation propagates the business exception for an unsupported range',
      'A',
      ['Authenticated ADMIN user invokes AdminDashboardController.getOverview'],
      { range: '90d' },
      [],
      ['BadRequestException: Unsupported dashboard range'],
    ),
    makeCase(
      'EP-003 UTC05 validation propagates a temporary analytics outage',
      'A',
      ['Authenticated ADMIN user invokes AdminDashboardController.getOverview'],
      { range: '30d' },
      [],
      ['ServiceUnavailableException: Analytics cache unavailable'],
    ),
    makeCase(
      'EP-003 UTC06 validation bubbles up unexpected repository failures',
      'A',
      ['Authenticated ADMIN user invokes AdminDashboardController.getOverview'],
      { range: '7d' },
      [],
      ['Error: dashboard query failed'],
    ),
    makeCase(
      'EP-003 UTC07 security declares JwtAuthGuard on the overview method',
      'A',
      ['Overview route is protected by authentication middleware'],
      {},
      [],
      ['401 Unauthorized'],
    ),
    makeCase(
      'EP-003 UTC08 security restricts the overview method to ADMIN role metadata',
      'A',
      ['Caller is authenticated as a non-ADMIN role'],
      {},
      [],
      ['403 Forbidden: only ADMIN can access getOverview'],
    ),
  ],
  'EP-004': [
    makeCase(
      'EP-004 UTC01 happy path passes transformed query values to findAll',
      'N',
      ['Authenticated ADMIN user invokes AuditLogsController.findAll'],
      { action: 'EXPORT', errorOnly: true, limit: 5, page: 2 },
      ['returns paginated audit log list with transformed query filters'],
      [],
    ),
    makeCase(
      'EP-004 UTC02 edge case keeps DTO default page and limit values when filters are omitted',
      'B',
      [
        'Authenticated ADMIN user invokes AuditLogsController.findAll',
        'Caller omits optional filter inputs',
      ],
      {},
      ['returns paginated audit log list with page = 1 and limit = 20'],
      [],
    ),
    makeCase(
      'EP-004 UTC03 edge case preserves valid low-bound limit and statusCode inputs',
      'B',
      ['Authenticated ADMIN user invokes AuditLogsController.findAll'],
      { eventCategory: 'ERROR', limit: 1, statusCode: 500 },
      ['returns audit log list filtered by low-bound limit and statusCode'],
      [],
    ),
    makeCase(
      'EP-004 UTC04 validation rejects page values below 1 in GetAuditLogsDto',
      'A',
      ['Authenticated ADMIN user invokes AuditLogsController.findAll'],
      { page: 0 },
      [],
      ['BadRequestException: page fails DTO validation'],
    ),
    makeCase(
      'EP-004 UTC05 validation rejects unsupported riskLevel values in GetAuditLogsDto',
      'A',
      ['Authenticated ADMIN user invokes AuditLogsController.findAll'],
      { riskLevel: 'CRITICAL' },
      [],
      ['BadRequestException: riskLevel fails DTO validation'],
    ),
    makeCase(
      'EP-004 UTC06 validation rejects unsupported source values in GetAuditLogsDto',
      'A',
      ['Authenticated ADMIN user invokes AuditLogsController.findAll'],
      { source: 'MOBILE' },
      [],
      ['BadRequestException: source fails DTO validation'],
    ),
    makeCase(
      'EP-004 UTC07 security declares JwtAuthGuard on findAll',
      'A',
      ['Audit log list route is protected by authentication middleware'],
      {},
      [],
      ['401 Unauthorized'],
    ),
    makeCase(
      'EP-004 UTC08 security restricts findAll to ADMIN role metadata',
      'A',
      ['Caller is authenticated as CLIENT'],
      {},
      [],
      ['403 Forbidden: only ADMIN can access findAll'],
    ),
  ],
  'EP-005': [
    makeCase(
      'EP-005 UTC01 happy path exports JSON by default and writes the export audit log',
      'N',
      [
        'Authenticated ADMIN user invokes AuditLogsController.export',
        'Audit export service is available',
      ],
      { actorId: 'admin-100', format: 'json' },
      ['returns audit log export file with Content-Type = "application/json; charset=utf-8"'],
      [],
    ),
    makeCase(
      'EP-005 UTC02 edge case exports CSV with the expected attachment headers',
      'B',
      ['Authenticated ADMIN user invokes AuditLogsController.export'],
      { actorId: 'admin-100', format: 'csv' },
      ['returns audit log export file with Content-Type = "text/csv; charset=utf-8"'],
      [],
    ),
    makeCase(
      'EP-005 UTC03 edge case exports XLSX with the expected attachment headers',
      'B',
      ['Authenticated ADMIN user invokes AuditLogsController.export'],
      { actorId: 'admin-100', format: 'xlsx' },
      ['returns audit log export file with XLSX attachment headers'],
      [],
    ),
    makeCase(
      'EP-005 UTC04 validation rejects unsupported export format values in GetAuditLogsDto',
      'A',
      ['Authenticated ADMIN user invokes AuditLogsController.export'],
      { format: 'pdf' },
      [],
      ['BadRequestException: format fails DTO validation'],
    ),
    makeCase(
      'EP-005 UTC05 validation rejects pagination limit values below 1 in GetAuditLogsDto',
      'A',
      ['Authenticated ADMIN user invokes AuditLogsController.export'],
      { limit: 0 },
      [],
      ['BadRequestException: limit fails DTO validation'],
    ),
    makeCase(
      'EP-005 UTC06 validation bubbles up export service failures without sending a partial response',
      'A',
      ['Authenticated ADMIN user invokes AuditLogsController.export'],
      { actorId: 'admin-9', format: 'json' },
      [],
      ['Error: export serialization failed'],
    ),
    makeCase(
      'EP-005 UTC07 security declares JwtAuthGuard on export',
      'A',
      ['Audit export route is protected by authentication middleware'],
      {},
      [],
      ['401 Unauthorized'],
    ),
    makeCase(
      'EP-005 UTC08 security restricts export to ADMIN role metadata',
      'A',
      ['Caller is authenticated as CLIENT'],
      {},
      [],
      ['403 Forbidden: only ADMIN can access export'],
    ),
  ],
  'EP-007': [
    makeCase(
      'EP-007 UTC01 happy path returns the correlated timeline for an audit log id',
      'N',
      ['Authenticated ADMIN user invokes AuditLogsController.getTimeline'],
      { id: 'audit-1' },
      ['returns correlated timeline payload for audit log "audit-1"'],
      [],
    ),
    makeCase(
      'EP-007 UTC02 edge case returns a single-entry request correlation timeline',
      'B',
      ['Authenticated ADMIN user invokes AuditLogsController.getTimeline'],
      { id: 'audit-1' },
      ['returns single-entry timeline with correlationType = "requestId"'],
      [],
    ),
    makeCase(
      'EP-007 UTC03 edge case returns an actor-scoped timeline when requestId is absent',
      'B',
      ['Authenticated ADMIN user invokes AuditLogsController.getTimeline'],
      { id: 'audit-2' },
      ['returns actor-scoped timeline with correlationType = "actorId"'],
      [],
    ),
    makeCase(
      'EP-007 UTC04 validation propagates the audit-log not-found business exception',
      'A',
      ['Authenticated ADMIN user invokes AuditLogsController.getTimeline'],
      { id: 'missing-log' },
      [],
      ['NotFoundException: Audit log not found'],
    ),
    makeCase(
      'EP-007 UTC05 validation propagates malformed timeline identifier errors',
      'A',
      ['Authenticated ADMIN user invokes AuditLogsController.getTimeline'],
      { id: 'bad-id' },
      [],
      ['BadRequestException: Malformed audit correlation id'],
    ),
    makeCase(
      'EP-007 UTC06 validation bubbles up unexpected timeline repository failures',
      'A',
      ['Authenticated ADMIN user invokes AuditLogsController.getTimeline'],
      { id: 'audit-500' },
      [],
      ['Error: timeline query failed'],
    ),
    makeCase(
      'EP-007 UTC07 security declares JwtAuthGuard on getTimeline',
      'A',
      ['Audit timeline route is protected by authentication middleware'],
      {},
      [],
      ['401 Unauthorized'],
    ),
    makeCase(
      'EP-007 UTC08 security restricts getTimeline to ADMIN role metadata',
      'A',
      ['Caller is authenticated as CLIENT'],
      {},
      [],
      ['403 Forbidden: only ADMIN can access getTimeline'],
    ),
  ],
  'EP-008': [
    makeCase(
      'EP-008 UTC01 happy path returns a detailed audit log view for the input id',
      'N',
      ['Authenticated ADMIN user invokes AuditLogsController.findOne'],
      { id: 'audit-1' },
      ['returns detailed audit log payload for id = "audit-1"'],
      [],
    ),
    makeCase(
      'EP-008 UTC02 edge case returns a detail payload with high-risk metadata',
      'B',
      ['Authenticated ADMIN user invokes AuditLogsController.findOne'],
      { id: 'audit-high' },
      ['returns audit detail payload with riskLevel = "HIGH"'],
      [],
    ),
    makeCase(
      'EP-008 UTC03 edge case returns a detail payload for anonymous actors',
      'B',
      ['Authenticated ADMIN user invokes AuditLogsController.findOne'],
      { id: 'audit-anon' },
      ['returns audit detail payload for anonymous actor metadata'],
      [],
    ),
    makeCase(
      'EP-008 UTC04 validation propagates the missing-detail business exception',
      'A',
      ['Authenticated ADMIN user invokes AuditLogsController.findOne'],
      { id: 'missing-log' },
      [],
      ['NotFoundException: Audit log not found'],
    ),
    makeCase(
      'EP-008 UTC05 validation propagates malformed detail identifier errors',
      'A',
      ['Authenticated ADMIN user invokes AuditLogsController.findOne'],
      { id: 'bad-id' },
      [],
      ['BadRequestException: Malformed audit log id'],
    ),
    makeCase(
      'EP-008 UTC06 validation bubbles up unexpected detail query failures',
      'A',
      ['Authenticated ADMIN user invokes AuditLogsController.findOne'],
      { id: 'audit-500' },
      [],
      ['Error: detail query failed'],
    ),
    makeCase(
      'EP-008 UTC07 security declares JwtAuthGuard on findOne',
      'A',
      ['Audit detail route is protected by authentication middleware'],
      {},
      [],
      ['401 Unauthorized'],
    ),
    makeCase(
      'EP-008 UTC08 security restricts findOne to ADMIN role metadata',
      'A',
      ['Caller is authenticated as CLIENT'],
      {},
      [],
      ['403 Forbidden: only ADMIN can access findOne'],
    ),
  ],
  'EP-031': [
    makeCase(
      'EP-031 UTC01 happy path creates a scheduled event with deduplicated participantUserIds',
      'N',
      [
        'Authenticated ADMIN user invokes CalendarController.createEvent',
        `Event startTime ${JSON.stringify(SAMPLE_START)} is before endTime ${JSON.stringify(SAMPLE_END)}`,
      ],
      {
        endTime: SAMPLE_END,
        participantUserIds: [OTHER_USER_ID, OTHER_USER_ID, USER_ID],
        priority: 'HIGH',
        startTime: SAMPLE_START,
        title: 'Kickoff meeting',
        type: 'PROJECT_MEETING',
      },
      ['returns "Event created" success payload'],
      [],
    ),
    makeCase(
      'EP-031 UTC02 edge case auto-schedules when useAutoSchedule is enabled',
      'B',
      ['Authenticated STAFF user invokes CalendarController.createEvent'],
      {
        endTime: SAMPLE_END,
        participantUserIds: [OTHER_USER_ID],
        startTime: SAMPLE_START,
        title: 'Auto schedule',
        type: 'PROJECT_MEETING',
        useAutoSchedule: true,
      },
      ['returns "Event auto-scheduled" success payload'],
      [],
    ),
    makeCase(
      'EP-031 UTC03 edge case skips availability lookup for organizer-only events',
      'B',
      ['Authenticated ADMIN user invokes CalendarController.createEvent'],
      {
        endTime: SAMPLE_END,
        startTime: SAMPLE_START,
        title: 'Solo block',
        type: 'INTERNAL_MEETING',
      },
      ['returns "Event created" success payload for organizer-only event'],
      [],
    ),
    makeCase(
      'EP-031 UTC04 validation rejects unsupported event type values in CreateCalendarEventDto',
      'A',
      ['Authenticated ADMIN user invokes CalendarController.createEvent'],
      {
        endTime: SAMPLE_END,
        startTime: SAMPLE_START,
        title: 'Broken event',
        type: 'INVALID_TYPE',
      },
      [],
      ['BadRequestException: type fails DTO validation'],
    ),
    makeCase(
      'EP-031 UTC05 validation rejects event times when startTime is not before endTime',
      'A',
      ['Authenticated ADMIN user invokes CalendarController.createEvent'],
      {
        endTime: SAMPLE_START,
        startTime: SAMPLE_END,
        title: 'Broken interval',
        type: 'PROJECT_MEETING',
      },
      [],
      ['BadRequestException: startTime must be before endTime'],
    ),
    makeCase(
      'EP-031 UTC06 validation rejects unavailable time selections',
      'A',
      [
        'Authenticated ADMIN user invokes CalendarController.createEvent',
        'No available slot matches the requested time window',
      ],
      {
        endTime: SAMPLE_END,
        participantUserIds: [OTHER_USER_ID],
        startTime: SAMPLE_START,
        title: 'Conflicting slot',
        type: 'PROJECT_MEETING',
      },
      [],
      ['BadRequestException: Selected time conflicts with availability'],
    ),
    makeCase(
      'EP-031 UTC07 security declares JwtAuthGuard on createEvent',
      'A',
      ['Calendar event creation route is protected by authentication middleware'],
      {},
      [],
      ['401 Unauthorized'],
    ),
    makeCase(
      'EP-031 UTC08 security blocks participant roles from creating dispute events directly',
      'A',
      ['Authenticated CLIENT user invokes CalendarController.createEvent'],
      {
        endTime: SAMPLE_END,
        startTime: SAMPLE_START,
        title: 'Hearing',
        type: 'DISPUTE_HEARING',
      },
      [],
      ['ForbiddenException: participant role cannot create dispute hearing directly'],
    ),
  ],
  'EP-032': [
    makeCase(
      'EP-032 UTC01 happy path returns enriched event items for the requested participantId',
      'N',
      ['Authenticated CLIENT user invokes CalendarController.listEvents'],
      { limit: 20, page: 1, participantId: USER_ID },
      ['returns paginated event list for participantId'],
      [],
    ),
    makeCase(
      'EP-032 UTC02 edge case defaults page and limit when those query values are omitted',
      'B',
      ['Authenticated CLIENT user invokes CalendarController.listEvents'],
      {},
      ['returns paginated event list with page = 1 and limit = 20'],
      [],
    ),
    makeCase(
      'EP-032 UTC03 edge case caps limit at 200 for oversized query input',
      'B',
      ['Authenticated CLIENT user invokes CalendarController.listEvents'],
      { limit: 999 },
      ['returns paginated event list with capped limit = 200'],
      [],
    ),
    makeCase(
      'EP-032 UTC04 validation rejects non-UUID organizerId values in CalendarEventFilterDto',
      'A',
      ['Authenticated CLIENT user invokes CalendarController.listEvents'],
      { organizerId: 'bad-id' },
      [],
      ['BadRequestException: organizerId fails DTO validation'],
    ),
    makeCase(
      'EP-032 UTC05 validation rejects malformed startDate values in CalendarEventFilterDto',
      'A',
      ['Authenticated CLIENT user invokes CalendarController.listEvents'],
      { startDate: 'not-a-date' },
      [],
      ['BadRequestException: startDate fails DTO validation'],
    ),
    makeCase(
      'EP-032 UTC06 validation rejects limit values smaller than 1 in CalendarEventFilterDto',
      'A',
      ['Authenticated CLIENT user invokes CalendarController.listEvents'],
      { limit: 0 },
      [],
      ['BadRequestException: limit fails DTO validation'],
    ),
    makeCase(
      'EP-032 UTC07 security declares JwtAuthGuard on listEvents',
      'A',
      ['Calendar event listing route is protected by authentication middleware'],
      {},
      [],
      ['401 Unauthorized'],
    ),
    makeCase(
      'EP-032 UTC08 security scopes the query to the current user when no subject filter is supplied',
      'A',
      ['Authenticated CLIENT user invokes CalendarController.listEvents without subject filter'],
      {},
      ['returns event query scoped to the current user context'],
      [],
    ),
  ],
  'EP-033': [
    makeCase(
      'EP-033 UTC01 happy path updates an existing event and syncs the changed range',
      'N',
      ['Authenticated CLIENT user owns the target event'],
      {
        endTime: SAMPLE_END,
        id: EVENT_ID,
        startTime: SAMPLE_START,
        title: 'Updated title',
      },
      ['returns updated event payload and syncs the changed time range'],
      [],
    ),
    makeCase(
      'EP-033 UTC02 edge case supports partial updates without altering existing timing',
      'B',
      ['Authenticated CLIENT user owns the target event'],
      { id: EVENT_ID, title: 'Partial update title' },
      ['returns updated event payload without changing startTime or endTime'],
      [],
    ),
    makeCase(
      'EP-033 UTC03 edge case allows staff to update another organizer event',
      'B',
      ['Authenticated STAFF user manages another organizer event'],
      { id: EVENT_ID, title: 'Managed event update' },
      ['returns updated event payload for delegated staff update'],
      [],
    ),
    makeCase(
      'EP-033 UTC04 validation rejects malformed UUID values for the id param',
      'A',
      ['Authenticated CLIENT user invokes CalendarController.updateEvent'],
      { id: 'bad-id' },
      [],
      ['BadRequestException: id must be a UUID'],
    ),
    makeCase(
      'EP-033 UTC05 validation returns 404 when the target event is missing',
      'A',
      ['Authenticated CLIENT user invokes CalendarController.updateEvent'],
      { id: EVENT_ID },
      [],
      ['NotFoundException: Event not found'],
    ),
    makeCase(
      'EP-033 UTC06 validation rejects updates for completed or cancelled events',
      'A',
      ['Target event is already CANCELLED'],
      { id: EVENT_ID, title: 'Attempted update' },
      [],
      ['BadRequestException: Completed or cancelled events cannot be updated'],
    ),
    makeCase(
      'EP-033 UTC07 security declares JwtAuthGuard on updateEvent',
      'A',
      ['Calendar event update route is protected by authentication middleware'],
      {},
      [],
      ['401 Unauthorized'],
    ),
    makeCase(
      'EP-033 UTC08 security blocks non-owner clients from updating another organizer event',
      'A',
      ['Authenticated CLIENT user is not the organizer of the target event'],
      { id: EVENT_ID, title: 'Unauthorized update' },
      [],
      ['ForbiddenException: only the organizer, staff, or admin can update this event'],
    ),
  ],
  'EP-034': [
    makeCase(
      'EP-034 UTC01 happy path creates a manual reschedule request for the requester',
      'N',
      ['Authenticated CLIENT user is a participant of the target event'],
      {
        eventId: EVENT_ID,
        id: EVENT_ID,
        proposedTimeSlots: [SAMPLE_START],
        reason: 'Need a new slot',
        useAutoSchedule: false,
      },
      ['returns created reschedule request payload'],
      [],
    ),
    makeCase(
      'EP-034 UTC02 edge case auto-processes the request when useAutoSchedule is enabled',
      'B',
      ['Authenticated CLIENT user is the organizer of the target event'],
      {
        eventId: EVENT_ID,
        id: EVENT_ID,
        proposedTimeSlots: [SAMPLE_START],
        reason: 'Auto schedule me',
        useAutoSchedule: true,
      },
      ['returns auto-processed reschedule request payload'],
      [],
    ),
    makeCase(
      'EP-034 UTC03 edge case allows the organizer to submit the request without a participant row',
      'B',
      ['Authenticated CLIENT user is the organizer of the target event'],
      {
        eventId: EVENT_ID,
        id: EVENT_ID,
        proposedTimeSlots: [SAMPLE_START],
        reason: 'Organizer-only request',
      },
      ['returns created reschedule request payload without participant row'],
      [],
    ),
    makeCase(
      'EP-034 UTC04 validation rejects malformed UUID values for the event id param',
      'A',
      ['Authenticated CLIENT user invokes CalendarController.requestReschedule'],
      { id: 'bad-id' },
      [],
      ['BadRequestException: id must be a UUID'],
    ),
    makeCase(
      'EP-034 UTC05 validation rejects mismatched body eventId and URL id inputs',
      'A',
      ['Authenticated CLIENT user invokes CalendarController.requestReschedule'],
      { eventId: OTHER_EVENT_ID, id: EVENT_ID },
      [],
      ['BadRequestException: eventId in body must match the URL id'],
    ),
    makeCase(
      'EP-034 UTC06 validation rejects more than three proposedTimeSlots entries',
      'A',
      ['Authenticated CLIENT user invokes CalendarController.requestReschedule'],
      {
        id: EVENT_ID,
        proposedTimeSlots: [SAMPLE_START, SAMPLE_END, '2026-04-01T11:00:00.000Z', '2026-04-01T12:00:00.000Z'],
      },
      [],
      ['BadRequestException: proposedTimeSlots cannot contain more than 3 entries'],
    ),
    makeCase(
      'EP-034 UTC07 security declares JwtAuthGuard on requestReschedule',
      'A',
      ['Calendar reschedule request route is protected by authentication middleware'],
      {},
      [],
      ['401 Unauthorized'],
    ),
    makeCase(
      'EP-034 UTC08 security blocks non-participants from requesting a reschedule',
      'A',
      ['Authenticated CLIENT user is not a participant of the target event'],
      { id: EVENT_ID },
      [],
      ['ForbiddenException: only participants or the organizer can request a reschedule'],
    ),
  ],
  'EP-035': [
    makeCase(
      'EP-035 UTC01 happy path returns a paginated reschedule request list',
      'N',
      ['Authenticated STAFF user invokes CalendarController.listRescheduleRequests'],
      { eventId: EVENT_ID, page: '1', requesterId: USER_ID, status: 'PENDING', limit: '10' },
      ['returns paginated reschedule request list'],
      [],
    ),
    makeCase(
      'EP-035 UTC02 edge case normalizes invalid page and limit values to safe defaults',
      'B',
      ['Authenticated STAFF user invokes CalendarController.listRescheduleRequests'],
      { page: 'abc', limit: '0' },
      ['returns reschedule request list with page = 1 and limit = 20'],
      [],
    ),
    makeCase(
      'EP-035 UTC03 edge case returns an empty list when no requests match the filters',
      'B',
      ['Authenticated STAFF user invokes CalendarController.listRescheduleRequests'],
      { page: '1', limit: '20' },
      ['returns empty reschedule request list'],
      [],
    ),
    makeCase(
      'EP-035 UTC04 validation rejects unsupported reschedule status values',
      'A',
      ['Authenticated STAFF user invokes CalendarController.listRescheduleRequests'],
      { status: 'DONE' },
      [],
      ['BadRequestException: Invalid reschedule request status'],
    ),
    makeCase(
      'EP-035 UTC05 validation rejects lower-case status values that do not match the enum',
      'A',
      ['Authenticated STAFF user invokes CalendarController.listRescheduleRequests'],
      { status: 'pending' },
      [],
      ['BadRequestException: Invalid reschedule request status'],
    ),
    makeCase(
      'EP-035 UTC06 validation bubbles up repository failures during request listing',
      'A',
      ['Authenticated STAFF user invokes CalendarController.listRescheduleRequests'],
      { page: '1', limit: '20' },
      [],
      ['Error: reschedule list failed'],
    ),
    makeCase(
      'EP-035 UTC07 security declares JwtAuthGuard on listRescheduleRequests',
      'A',
      ['Reschedule request listing route is protected by authentication middleware'],
      {},
      [],
      ['401 Unauthorized'],
    ),
    makeCase(
      'EP-035 UTC08 security restricts listRescheduleRequests to STAFF and ADMIN roles',
      'A',
      ['Caller is authenticated as CLIENT'],
      {},
      [],
      ['403 Forbidden: only STAFF or ADMIN can access listRescheduleRequests'],
    ),
  ],
  'EP-036': [
    makeCase(
      'EP-036 UTC01 happy path approves a pending request through auto scheduling',
      'N',
      ['Authenticated STAFF user processes a PENDING reschedule request'],
      { action: 'approve', requestId: REQUEST_ID },
      ['returns "Reschedule approved"'],
      [],
    ),
    makeCase(
      'EP-036 UTC02 edge case rejects the request and records processNote',
      'B',
      ['Authenticated ADMIN user processes a PENDING reschedule request'],
      { action: 'reject', processNote: 'Not enough participants', requestId: REQUEST_ID },
      ['returns "Reschedule request rejected"'],
      [],
    ),
    makeCase(
      'EP-036 UTC03 edge case processes a manual selectedNewStartTime value',
      'B',
      ['Authenticated ADMIN user processes a PENDING reschedule request'],
      {
        action: 'approve',
        processNote: 'Approved manually',
        requestId: REQUEST_ID,
        selectedNewStartTime: SAMPLE_START,
      },
      ['returns manually processed reschedule approval'],
      [],
    ),
    makeCase(
      'EP-036 UTC04 validation rejects malformed requestId values in ProcessRescheduleRequestDto',
      'A',
      ['Authenticated STAFF user invokes CalendarController.processRescheduleRequest'],
      { action: 'approve', requestId: 'bad-id' },
      [],
      ['BadRequestException: requestId fails DTO validation'],
    ),
    makeCase(
      'EP-036 UTC05 validation returns 404 when the reschedule request does not exist',
      'A',
      ['Authenticated STAFF user invokes CalendarController.processRescheduleRequest'],
      { action: 'approve', requestId: REQUEST_ID },
      [],
      ['NotFoundException: Reschedule request not found'],
    ),
    makeCase(
      'EP-036 UTC06 validation rejects non-pending reschedule requests',
      'A',
      ['Target reschedule request is already REJECTED'],
      { action: 'approve', requestId: REQUEST_ID },
      [],
      ['BadRequestException: Reschedule request already processed'],
    ),
    makeCase(
      'EP-036 UTC07 security declares JwtAuthGuard on processRescheduleRequest',
      'A',
      ['Reschedule processing route is protected by authentication middleware'],
      {},
      [],
      ['401 Unauthorized'],
    ),
    makeCase(
      'EP-036 UTC08 security restricts processRescheduleRequest to STAFF and ADMIN roles',
      'A',
      ['Caller is authenticated as CLIENT'],
      {},
      [],
      ['403 Forbidden: only STAFF or ADMIN can access processRescheduleRequest'],
    ),
  ],
  'EP-037': [
    makeCase(
      'EP-037 UTC01 happy path records an invite response for the participant',
      'N',
      ['Authenticated CLIENT user is the participant of the target event'],
      { id: EVENT_ID, participantId: PARTICIPANT_ID, response: 'accept' },
      ['returns recorded invite response payload'],
      [],
    ),
    makeCase(
      'EP-037 UTC02 edge case lets admins respond on behalf of the participant',
      'B',
      ['Authenticated ADMIN user responds on behalf of the participant'],
      { id: EVENT_ID, participantId: PARTICIPANT_ID, response: 'decline', userId: ADMIN_ID },
      ['returns recorded invite response payload for admin override'],
      [],
    ),
    makeCase(
      'EP-037 UTC03 edge case lets staff respond on behalf of the participant',
      'B',
      ['Authenticated STAFF user responds on behalf of the participant'],
      { id: EVENT_ID, participantId: PARTICIPANT_ID, response: 'accept', userId: USER_ID },
      ['returns recorded invite response payload for staff override'],
      [],
    ),
    makeCase(
      'EP-037 UTC04 validation rejects malformed UUID values for the event id param',
      'A',
      ['Authenticated CLIENT user invokes CalendarController.respondInvite'],
      { id: 'bad-id' },
      [],
      ['BadRequestException: id must be a UUID'],
    ),
    makeCase(
      'EP-037 UTC05 validation returns 404 when the participant link does not exist',
      'A',
      ['Authenticated CLIENT user invokes CalendarController.respondInvite'],
      { id: EVENT_ID, participantId: PARTICIPANT_ID, response: 'accept' },
      [],
      ['NotFoundException: Event participant not found'],
    ),
    makeCase(
      'EP-037 UTC06 validation rejects participant ids that belong to another event',
      'A',
      ['Participant link belongs to another event'],
      { id: EVENT_ID, participantId: PARTICIPANT_ID, response: 'accept' },
      [],
      ['BadRequestException: Participant does not belong to the specified event'],
    ),
    makeCase(
      'EP-037 UTC07 security declares JwtAuthGuard on respondInvite',
      'A',
      ['Invite response route is protected by authentication middleware'],
      {},
      [],
      ['401 Unauthorized'],
    ),
    makeCase(
      'EP-037 UTC08 security blocks another participant from responding without elevated role',
      'A',
      ['Authenticated CLIENT user is not the participant linked to the invite'],
      { id: EVENT_ID, participantId: PARTICIPANT_ID, response: 'accept' },
      [],
      ['ForbiddenException: only the participant, staff, or admin can respond to this invite'],
    ),
  ],
};

export const getManualCaseDefinitions = (code: string) => MANUAL_CASES[code];
